### ISSUE TITLE
Add support for YOLOv8

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso#128]
Description:

YOLO has been upgraded and we risk deprecations causing issues down the line if we do not keep up. Yolov8 is now available for both the Ultralytics version of YOLO and the tracker submodule.

**Comment by victor-wildlife** [comment]
@jannesgg and @Diewertje11 this [fine-tune guide more FiftyOne](https://docs.voxel51.com/tutorials/yolov8.html) might have something helpful?

**Comment by jannesgg** [comment]
This will be done as part of cloudina migration issue. Closing this for now.
