### ISSUE TITLE
Dockerfile nvidia starting image

### ISSUE THREAD

**Issue by Diewertje11** [ocean-data-factory-sweden/kso#198]
The dockerfile (the one that is for both repositories combined (data-management) and (object-detection)) currently first loads the nvidia cuda devel docker image to start with, in order to build the ffmpeg from scratch.

Then it starts over from a new image, copies the final installation of the ffmpeg and builds up the rest of the environment. In theory this should be possible to do with the runtime image, which has the advantage that it is smaller. However, when trying that, the dockerfile could not get through the builder test on github since it ran out of disk. This is the error that occurred:
 

![Image](https://user-images.githubusercontent.com/47739872/245393729-773695db-a5aa-4230-b925-f306f3512b96.jpg)

This error is resolved by using the devel image for a second time, instead of loading in this new image. However, now we end up with a larger image at the end (which is not a problem), but it is not the neatest solution. So this is something we can take a look at again in the future.

**Comment by jannesgg** [comment]
@Diewertje11 Have a look at the Github workflow changes. I have added a step which clears up some memory when the runner starts up, which has fixed some of these out of memory errors for me. Feel free to test this with the new workflow.

**Comment by Diewertje11** [comment]
This indeed fixed the issue. I have changed the Dockerfile so that it can use the runtime image now the second time. See PR #212
