### ISSUE TITLE
Notebook 4+8: Generalize workflow and species selection

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso#204]
To select the species and aggregation factors is done in a different order in Notebook 4 and 8, and they always display all options that do not give any annotations. The idea is to make it the same for both notebooks, and filter the options first on if there are annotations available or not. This can be done on zoo_info_dict. I am working on this.

**Comment by victor-wildlife** [comment]
@Diewertje11 Are you still working on this. I started to tidy up the different functions to retrieve information from Zooniverse and committed the changes to the fix_spyfish_subjects branch but I think it will be good to go through the changes required together when you have the time
