### ISSUE TITLE
Tutorial 3 issue with producing sample clips

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/kso#237]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## 🐛 Bug
Seems to be something that has not been defined.

## To Reproduce (REQUIRED)

pp.generate_zoo_clips(
    movie_name=pp.movie_selected,
    movie_path=pp.movie_path,
    is_example=True,
    use_gpu=gpu_available.result,
)
Output:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File ~/.local/lib/python3.8/site-packages/ipywidgets/widgets/interaction.py:257, in interactive.update(self, *args)
    255     value = widget.get_interact_value()
    256     self.kwargs[widget._kwarg] = value
--> 257 self.result = self.f(**self.kwargs)
    258 show_inline_matplotlib_plots()
    259 if self.auto_display and self.result is not None:

File /usr/src/app/kso/kso_utils/kso_utils/widgets.py:1182, in n_random_clips(clip_length, n_clips)
   1179 def n_random_clips(clip_length, n_clips):
   1180     # Create a list of starting points for n number of clips
   1181     # movie_df is currently missing here
-> 1182     duration_movie = int(movie_df["duration"].values[0])
   1183     starting_clips = random.sample(range(0, duration_movie, clip_length), n_clips)
   1185     # Seave the outputs in a dictionary

NameError: name 'movie_df' is not defined

Number of modifications:
0

```

![image](https://github.com/ocean-data-factory-sweden/kso/assets/89446587/286e0d8b-7d2c-478f-85cf-a93d8616cce3)

## Expected behavior
the expected behaviour is to be able to extract sample clips from the video

**Comment by jannesgg** [comment]
@victor-wildlife This is an issue that I also encountered and seems to be linked to code changes in the random clip selection widgets. Would you mind having a look to see if you could find a potential solution to getting the movie duration in this case?
