### ISSUE TITLE
Migration issues - Cloudina

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso#287]
- [x] ipysheet does not work with Jupyterlab as it currently stands (tutorial 1) - We move forward with idea that users will use Jupyter Notebook instead of JupyterLab directly for now. 
- [x] ipywidgets needs to be upgraded to at least 8.0.4
- [x] Fix asyncio functions (don't seem to work in Jupyter lab). See pp.preview_media() as example. 
- [x] Add Colab-specific requirements file (@victor-wildlife)
- [ ] Test tuts in colab

**Comment by victor-wildlife** [comment]
@jannesgg if the yolov5 submodule is still tricky maybe (the way fiftyone has integrated YOLOv8)[https://movingworlds.org/rep/browse/project/3549] might give you an idea on how easy it might be to just move to the yolov8

**Comment by jannesgg** [comment]
@victor-wildlife Thanks for the suggestion, I'm not sure that is the correct link as it points to Wildlife.aI? I will be changing to yolov8 with the migration so we can avoid the submodules altogether. :)

**Comment by victor-wildlife** [comment]
@jannesgg yes, this should eb the right link https://docs.voxel51.com/integrations/ultralytics.html

**Comment by victor-wildlife** [comment]
@jannesgg FYI- I have added a couple of commits to the fix-migration-issues branch

**Comment by victor-wildlife** [comment]
@jannesgg I added the colab-specific requirements file and the code in the first cell of the tutorials to install the requirements. You will need to approve pull request #306 and get the latest changes to the fix-cloudina branch. Let me know if you have any questions

**Comment by jannesgg** [comment]
Merged.
