### ISSUE TITLE
Module ultralytics, train and other can't be imported #6 and #9

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#310]
When initialising the MLP we get some ERROR:root messages.

Is this something we should remove?

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/ecb30933-acc5-41d6-824e-75d8e24c7d41)

**Comment by jannesgg** [comment]
@victor-wildlife Seems like there are some new packages that you do not have installed. Could you run pip install -r requirements.txt again and see if the messages disappear?

**Comment by victor-wildlife** [comment]
OK, yeah, that solved the issue. I will also update the colab requirements so that we can run the ML tutorials in Colab
