### ISSUE TITLE
Create a ML Model Zoo

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#313]
We should create a standalone Model Hub where people can share their models and it's easy to run them. Maybe following similar model hubs like Ersilia (https://ersilia.gitbook.io/ersilia-book/)? They even have a colab notebook approach (https://github.com/ersilia-os/ersilia/blob/master/notebooks/ersilia-on-colab.ipynb)

**Comment by jannesgg** [comment]
We have Zenodo for now. Closing.
