### ISSUE TITLE
Issue extracting frames from .mpg file in tutorial 4

### ISSUE THREAD

**Issue by ShrimpFather7** [ocean-data-factory-sweden/kso#330]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
```
# Generate suitable frames for upload by modifying initial frames
pp.generate_custom_frames(
    input_path=input_folder.selected,
    output_path=output_folder.selected,
    skip_start=1,
    skip_end=40,
    num_frames=50,
    frames_skip=None,
)
```

Output:
```
AttributeError                            Traceback (most recent call last)
File /usr/src/app/kso-dev/kso_utils/project.py:973, in ProjectProcessor.generate_custom_frames.<locals>.on_button_clicked(b)
    969 def on_button_clicked(b):
    970     movie_files = sorted(
    971         [
    972             f
--> 973             for f in input_path.iterdir()
    974             if f.is_file()
    975             and f.suffix.lower() in [".mov", ".mp4", ".avi", ".mkv", ".mpg"]
    976         ]
    977     )
    979     results = g_utils.parallel_map(
    980         kso_widgets.extract_custom_frames,
    981         movie_files,
   (...)
    989         ),
    990     )
    991     if len(results) > 0:

AttributeError: 'str' object has no attribute 'iterdir'
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by ShrimpFather7** [comment]
@jannesgg

**Comment by jannesgg** [comment]
@ShrimpFather7 On my side, this was fixed 2 days ago as part of #327. Could you make sure you are on the dev branch and also do a git pull just to be safe?

**Comment by ShrimpFather7** [comment]
@jannesgg When running through the tutorial again I've been running through issues with compressing the frames. I get the following issue:

  File <string>:1
    ffmpeg.input('/mimer/NOBACKUP/groups/snic2021-6-9/tmp_dir/KSO_shallow_frames_CN/video-HD_CAM_1-2022-07-15T08-54-30-401_frame_7923.jpg').output('/mimer/NOBACKUP/groups/snic2021-6-9/tmp_dir/frames/modified_Dead man's fingers_frames/video-HD_CAM_1-2022-07-15T08-54-30-401_frame_7923.jpg', q=25)
                                                                                                                                                                                                                         ^
SyntaxError: invalid syntax

I'm not sure if this is related to the issue you were talking about or if it's a new one. But this has gotten in the way of me reaching the "Upload frames to zooniverse" cell. When I run that cell however, I reach this error:

IntCastingNaNError                        Traceback (most recent call last)
Cell In[18], line 1
----> 1 pp.upload_zoo_subjects("frame")

File /usr/src/app/kso-dev/kso_utils/project.py:781, in ProjectProcessor.upload_zoo_subjects(self, subject_type)
    778     logging.info(f"Clips temporarily stored locally has been removed")
    780 elif subject_type == "frame":
--> 781     upload_df = zoo_utils.set_zoo_frame_metadata(
    782         project=self.project,
    783         db_connection=self.db_connection,
    784         df=self.generated_frames,
    785         species_list=self.species_of_interest,
    786         csv_paths=self.csv_paths,
    787     )
    788     zoo_utils.upload_frames_to_zooniverse(
    789         project=self.project,
    790         upload_to_zoo=upload_df,
    791         species_list=self.species_of_interest,
    792     )
    794 else:

File /usr/src/app/kso-dev/kso_utils/zooniverse_utils.py:1826, in set_zoo_frame_metadata(project, db_connection, df, species_list, csv_paths)
   1824 # Set project-specific metadata
   1825 if project.Zooniverse_number == 9747:
-> 1826     df = add_db_info_to_df(
   1827         project, db_connection, csv_paths, df, "sites", "id, siteName"
   1828     )
   1829     upload_to_zoo = df[
   1830         [
   1831             "frame_path",
   (...)
   1837         ]
   1838     ]
   1840 elif project_name == "SGU":

File /usr/src/app/kso-dev/kso_utils/db_utils.py:515, in add_db_info_to_df(project, conn, csv_paths, df, table_name, cols_interest)
    513 # Ensure id columns that are going to be used to merge are int
    514 if "id" in left_on_col:
--> 515     df[left_on_col] = df[left_on_col].astype(float).astype(int)
    517 # Combine the original and sqldf dfs
    518 comb_df = pd.merge(
    519     df, sql_df, how="left", left_on=left_on_col, right_on=right_on_col
    520 )

File /usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:5920, in NDFrame.astype(self, dtype, copy, errors)
   5913     results = [
   5914         self.iloc[:, i].astype(dtype, copy=copy)
   5915         for i in range(len(self.columns))
   5916     ]
   5918 else:
   5919     # else, only a single dtype is given
-> 5920     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   5921     return self._constructor(new_data).__finalize__(self, method="astype")
   5923 # GH 33113: handle empty frame or series

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py:419, in BaseBlockManager.astype(self, dtype, copy, errors)
    418 def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
--> 419     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py:304, in BaseBlockManager.apply(self, f, align_keys, ignore_failures, **kwargs)
    302         applied = b.apply(f, **kwargs)
    303     else:
--> 304         applied = getattr(b, f)(**kwargs)
    305 except (TypeError, NotImplementedError):
    306     if not ignore_failures:

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py:582, in Block.astype(self, dtype, copy, errors)
    564 """
    565 Coerce to the new dtype.
    566 
   (...)
    578 Block
    579 """
    580 values = self.values
--> 582 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    584 new_values = maybe_coerce_values(new_values)
    585 newb = self.make_block(new_values)

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1292, in astype_array_safe(values, dtype, copy, errors)
   1289     dtype = dtype.numpy_dtype
   1291 try:
-> 1292     new_values = astype_array(values, dtype, copy=copy)
   1293 except (ValueError, TypeError):
   1294     # e.g. astype_nansafe can fail on object-dtype of strings
   1295     #  trying to convert to float
   1296     if errors == "ignore":

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1237, in astype_array(values, dtype, copy)
   1234     values = values.astype(dtype, copy=copy)
   1236 else:
-> 1237     values = astype_nansafe(values, dtype, copy=copy)
   1239 # in pandas we don't store numpy str dtypes, so convert to object
   1240 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1148, in astype_nansafe(arr, dtype, copy, skipna)
   1145     raise TypeError(f"cannot astype a timedelta from [{arr.dtype}] to [{dtype}]")
   1147 elif np.issubdtype(arr.dtype, np.floating) and np.issubdtype(dtype, np.integer):
-> 1148     return astype_float_to_int_nansafe(arr, dtype, copy)
   1150 elif is_object_dtype(arr.dtype):
   1151 
   1152     # work around NumPy brokenness, #1987
   1153     if np.issubdtype(dtype.type, np.integer):

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1193, in astype_float_to_int_nansafe(values, dtype, copy)
   1189 """
   1190 astype with a check preventing converting NaN to an meaningless integer value.
   1191 """
   1192 if not np.isfinite(values).all():
-> 1193     raise IntCastingNaNError(
   1194         "Cannot convert non-finite values (NA or inf) to integer"
   1195     )
   1196 return values.astype(dtype, copy=copy)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

**Comment by jannesgg** [comment]
@ShrimpFather7 This issue is probably due to the fact that there is a quote in the folder name "modified_Dead man's" which creates a problem for the string creation. I will see if I can solve this somehow and update here if I find a solution.

**Comment by ShrimpFather7** [comment]
@jannesgg The first error was resolved by changing the species name, thanks! Hope it goes well with the other issue :)

**Comment by jannesgg** [comment]
@ShrimpFather7 I have made a quick fix now, please try git pull and let me know how it goes.

**Comment by ShrimpFather7** [comment]
Tried a git pull and ran in kso-dev. Still seems like the same error.

IntCastingNaNError                        Traceback (most recent call last)
Cell In[13], line 1
----> 1 pp.upload_zoo_subjects("frame")

File /usr/src/app/kso-dev/kso_utils/project.py:781, in ProjectProcessor.upload_zoo_subjects(self, subject_type)
    778     logging.info(f"Clips temporarily stored locally has been removed")
    780 elif subject_type == "frame":
--> 781     upload_df = zoo_utils.set_zoo_frame_metadata(
    782         project=self.project,
    783         db_connection=self.db_connection,
    784         df=self.generated_frames,
    785         species_list=self.species_of_interest,
    786         csv_paths=self.csv_paths,
    787     )
    788     zoo_utils.upload_frames_to_zooniverse(
    789         project=self.project,
    790         upload_to_zoo=upload_df,
    791         species_list=self.species_of_interest,
    792     )
    794 else:

File /usr/src/app/kso-dev/kso_utils/zooniverse_utils.py:1826, in set_zoo_frame_metadata(project, db_connection, df, species_list, csv_paths)
   1824 # Set project-specific metadata
   1825 if project.Zooniverse_number == 9747:
-> 1826     df = add_db_info_to_df(
   1827         project, db_connection, csv_paths, df, "sites", "id, siteName"
   1828     )
   1829     upload_to_zoo = df[
   1830         [
   1831             "frame_path",
   (...)
   1837         ]
   1838     ]
   1840 elif project_name == "SGU":

File /usr/src/app/kso-dev/kso_utils/db_utils.py:515, in add_db_info_to_df(project, conn, csv_paths, df, table_name, cols_interest)
    513 # Ensure id columns that are going to be used to merge are int
    514 if "id" in left_on_col:
--> 515     df[left_on_col] = df[left_on_col].astype(float).astype(int)
    517 # Combine the original and sqldf dfs
    518 comb_df = pd.merge(
    519     df, sql_df, how="left", left_on=left_on_col, right_on=right_on_col
    520 )

File /usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:5920, in NDFrame.astype(self, dtype, copy, errors)
   5913     results = [
   5914         self.iloc[:, i].astype(dtype, copy=copy)
   5915         for i in range(len(self.columns))
   5916     ]
   5918 else:
   5919     # else, only a single dtype is given
-> 5920     new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
   5921     return self._constructor(new_data).__finalize__(self, method="astype")
   5923 # GH 33113: handle empty frame or series

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py:419, in BaseBlockManager.astype(self, dtype, copy, errors)
    418 def astype(self: T, dtype, copy: bool = False, errors: str = "raise") -> T:
--> 419     return self.apply("astype", dtype=dtype, copy=copy, errors=errors)

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py:304, in BaseBlockManager.apply(self, f, align_keys, ignore_failures, **kwargs)
    302         applied = b.apply(f, **kwargs)
    303     else:
--> 304         applied = getattr(b, f)(**kwargs)
    305 except (TypeError, NotImplementedError):
    306     if not ignore_failures:

File /usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py:582, in Block.astype(self, dtype, copy, errors)
    564 """
    565 Coerce to the new dtype.
    566 
   (...)
    578 Block
    579 """
    580 values = self.values
--> 582 new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
    584 new_values = maybe_coerce_values(new_values)
    585 newb = self.make_block(new_values)

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1292, in astype_array_safe(values, dtype, copy, errors)
   1289     dtype = dtype.numpy_dtype
   1291 try:
-> 1292     new_values = astype_array(values, dtype, copy=copy)
   1293 except (ValueError, TypeError):
   1294     # e.g. astype_nansafe can fail on object-dtype of strings
   1295     #  trying to convert to float
   1296     if errors == "ignore":

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1237, in astype_array(values, dtype, copy)
   1234     values = values.astype(dtype, copy=copy)
   1236 else:
-> 1237     values = astype_nansafe(values, dtype, copy=copy)
   1239 # in pandas we don't store numpy str dtypes, so convert to object
   1240 if isinstance(dtype, np.dtype) and issubclass(values.dtype.type, str):

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1148, in astype_nansafe(arr, dtype, copy, skipna)
   1145     raise TypeError(f"cannot astype a timedelta from [{arr.dtype}] to [{dtype}]")
   1147 elif np.issubdtype(arr.dtype, np.floating) and np.issubdtype(dtype, np.integer):
-> 1148     return astype_float_to_int_nansafe(arr, dtype, copy)
   1150 elif is_object_dtype(arr.dtype):
   1151 
   1152     # work around NumPy brokenness, #1987
   1153     if np.issubdtype(dtype.type, np.integer):

File /usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/cast.py:1193, in astype_float_to_int_nansafe(values, dtype, copy)
   1189 """
   1190 astype with a check preventing converting NaN to an meaningless integer value.
   1191 """
   1192 if not np.isfinite(values).all():
-> 1193     raise IntCastingNaNError(
   1194         "Cannot convert non-finite values (NA or inf) to integer"
   1195     )
   1196 return values.astype(dtype, copy=copy)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

**Comment by jannesgg** [comment]
See e-mail. Closing issue for now. Re-open if necessary.
