### ISSUE TITLE
Verbose issue while running tut#9 with template project

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#332]
When running the detect_yolo function in Colab for the template project and after selecting the Spyfis_aotearoa_1, I ran into this issue.

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/8a7a8c9c-9840-423f-9643-6550de30e7ed)

@jannesgg have you come across this before?

I was working on the max_n_improvements branch

**Comment by jannesgg** [comment]
Related to latest=False, closing.
