### ISSUE TITLE
Tutorial 9 issue with choosing metrics

### ISSUE THREAD

**Issue by Bergylta** [ocean-data-factory-sweden/kso#333]
Before submitting a bug report, please be aware that your issue **must be reproducible** with all of the following, otherwise it is non-actionable, and we can not help you:
 - **Current repo**: run `git fetch && git status -uno` to check and `git pull` to update repo
 - **Common dataset**: coco.yaml or coco128.yaml
 - **Common environment**: Colab, Google Cloud, or Docker image. See https://github.com/ultralytics/yolov5#environments
 
If this is a custom dataset/training question you **must include** your `train*.jpg`, `test*.jpg` and `results.png` figures, or we can not help you. You can generate these with `utils.plot_results()`.

## To Reproduce (REQUIRED)

Input:
Folder for run and output: /mimer/NOBACKUP/groups/snic2021-6-9/tmp_dir/GU_gobies_round2_testing/GU_GARV_01/
```
statistics = t_utils.choose_statistics()
```

Output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 statistics = t_utils.choose_statistics()

AttributeError: module 'kso_utils.tutorials_utils' has no attribute 'choose_statistics'
```

## Expected behavior
A dropdown menu with the choices for statistics (such as max_n) should show up

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by victor-wildlife** [comment]
We are working on fixing this issue
