### ISSUE TITLE
Publish the project occurrences to GBIF

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/kso#336]
- [ ] Summarise the YOLO output to MAX count
- [ ] Combine the movie and site information maybe using [the bdc R package?](https://github.com/brunobrr/bdc/)
- [ ] Export to GBIF format
- [ ] Publish in Sweedish GBIF node
- [x] Add same logic to assign "clip" of "frame" subject_type to zooniverse_utils:1045 for non-KSO projects.

**Comment by victor-wildlife** [comment]
@Bergylta are there any observations from movies/species that you think we can publish in OBIS before the launch?

**Comment by jannesgg** [comment]
Published to GBIF. Re-open as necessary.
