### ISSUE TITLE
Only 5 movies mapped in KSO

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#366]
When running the Koster_Seafloor_Obs project in Cloudina the system can only map 5 out of the 141 movies. I don't think this is a Cloudina-related issue but something to do with the fpath column or the actual location of the movies?  

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/f74d391e-c79b-4b12-85f6-924b4d297eaf)

**Comment by jannesgg** [comment]
CSV has been fixed. Now mapping 80 movies.
