### ISSUE TITLE
Klippgrund missing location info

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#367]
Can either of you try updating the lat/lon values of the Klippgrund site from the Koster Seafloor Obs project using tut#1?
At the moment the location is set to 0,0

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/ed1383b9-075a-4291-9e0b-84598b86a63f)

**Comment by Bergylta** [comment]
@victor-wildlife seems to be something not quite working on the cloudina side in tut 1
when i try to do changes in tut 1 as we are supposed to do, i only get 
```
INFO:root:Checking if changes can be incorporated to the database
```
at the last part where one does the confirmation that the info is correct, and then the kernel goes idle

**Comment by Bergylta** [comment]
Klippgrund positional data has been added to the csv manually (the good old fashioned way), so now it is up to date with that 😃
