### ISSUE TITLE
Choose_footage doesn't display the movies

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#379]
We are still having issues with choose_footage to display the movies. I have created a separate choose_footage_display branch to ensure we have a working version before we submit changes to the dev branch

**Comment by jannesgg** [comment]
@victor-wildlife As an addition to this issue, large files do not seem to be displayed easily and cause the kernel to crash or a widget error. We need to find a way to deal with this either by putting a max size for video display or by somehow clearing the memory from the notebook.

**Comment by victor-wildlife** [comment]
Does this happen when trying to display movies stored in SNIC? I haven't had the issue when displaying movies temporarily exposed from AWS (via https). I think setting up a max video size might be the way to go though.

**Comment by jannesgg** [comment]
@victor-wildlife This currently happens with movies from Cloudina (GU specifically). These videos seem to be larger in general than the others we have worked with, which might be the reason behind this.

**Comment by jannesgg** [comment]
@victor-wildlife I have been revisiting this issue and for some reason I cannot get any of the videos to display now in Cloudina. Could you check whether you are having the same experience in Tutorial 1?

**Comment by victor-wildlife** [comment]
The videos display on my local computer and in Colab. [pip list output here](https://codeshare.io/ONWQvg) in case you can find any differences

**Comment by jannesgg** [comment]
@victor-wildlife I have now separated the selection widget from the display part as showing the movies was not working in Cloudina anymore, and this way we can ensure that users don't add too much memory to RAM (although this still might happen for very large movies).

**Comment by jannesgg** [comment]
We can make improvements to this in future but for now it is working adequately.
