### ISSUE TITLE
Video modifications don't work in tut#3

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#393]
Tut#3 creates clips but when asking to modify them (e.g. low zoo compression) it produces an ffmpeg error. Potentially because of path issues? 

I tried it in Cloudina with the dev branch and template project and got the following error.

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/81237d92-ecd1-40a1-86c6-1f0f9b2bcd27)

When I run it in Colab I don't get any error though.

**Comment by victor-wildlife** [comment]
This should be fixed when Cloudina has access to ffmpeg with Cuda (GPU) acceleration

**Comment by victor-wildlife** [comment]
@jannesgg do you know if there is a workaround to this issue? I tried using the A100 GPU (A100-1g.5gb) from the NZ HPC but it doesn't work

**Comment by jannesgg** [comment]
@victor-wildlife We have found that the A100's do not support FFMpeg encoding. If you have any T4 instances (or other compatible devices) available that should solve the issue. 
![Screenshot 2024-04-25 at 12 39 29](https://github.com/ocean-data-factory-sweden/kso/assets/36601086/ce9701fb-dadd-42b7-80d7-90fa97706522)
